wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1661785429
    t:
      1:
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 13
      - 16
      4: 3.9.13
      5: 0.12.19
      8:
      - 4
      - 5
cost:
  desc: null
  value: 0.001
env:
  desc: null
  value: psych_NegAffDay
eps:
  desc: null
  value: 1.0
eps_decay:
  desc: null
  value: 0.99995
lr:
  desc: null
  value: 1.0
min_eps:
  desc: null
  value: 0.0001
y:
  desc: null
  value: 0.99
